// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/update_password/data/repo_impl/update_password_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/app_data/common_response/reset_password_response.dart'
    as _i5;
import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/auth/data/datasource/local_data_source/auth_local_data_source_contract.dart'
    as _i8;
import 'package:fitness_app/features/update_password/data/data_sources/update_password_remote_ds_interface.dart'
    as _i2;
import 'package:fitness_app/features/update_password/data/models/update_password_request.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UpdatePasswordRemoteDsInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePasswordRemoteDsInterface extends _i1.Mock
    implements _i2.UpdatePasswordRemoteDsInterface {
  MockUpdatePasswordRemoteDsInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ResetPasswordResponse>> updatePassword(
          _i6.UpdatePasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [request],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.ResetPasswordResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.ResetPasswordResponse>>(
          this,
          Invocation.method(
            #updatePassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.ResetPasswordResponse>>);
}

/// A class which mocks [AuthLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSourceContract extends _i1.Mock
    implements _i8.AuthLocalDataSourceContract {
  MockAuthLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #cacheToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> checkSavedToken() => (super.noSuchMethod(
        Invocation.method(
          #checkSavedToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> cacheRememberMe(bool? rememberMe) => (super.noSuchMethod(
        Invocation.method(
          #cacheRememberMe,
          [rememberMe],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool getRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #getRememberMe,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> deleteRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #deleteRememberMe,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
