name: fitness_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependency_overrides:
  shared_preferences_android: 2.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  equatable:
  flutter_bloc:
  get_it:
  dio:
  shared_preferences:
  flutter_secure_storage:
  provider:
  retrofit:
  json_annotation: ^4.9.0
  injectable:
  logger:
  connectivity_plus:
  pretty_dio_logger:
  shimmer:
  intl:
  lottie:
  firebase_core:
  firebase_crashlytics:
  firebase_analytics:
  test:
  bloc_test:
  blur:
  flutter_svg:
  pinput:
  google_fonts: ^6.2.1
  numberpicker: ^2.1.2
  icons_plus: ^5.0.0
  smooth_page_indicator:
  google_generative_ai:
  flutter_svg_provider: ^1.0.7
  freezed_annotation: ^3.0.0
  hive_ce:
  hive_ce_flutter:
  uuid:
  path_provider:
  flutter_markdown: ^0.7.7+1
  skeletonizer:
  cached_network_image: ^3.2.0
  youtube_player_flutter: ^9.1.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.3
  retrofit_generator: ">=8.0.0 <10.0.0"
  injectable_generator:
  json_serializable:
  mockito:
  flutter_native_splash:
  flutter_launcher_icons:
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  hive_ce_generator:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: BalooThambi2
      fonts:
        - asset: assets/fonts/BalooThambi2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooThambi2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooThambi2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BalooThambi2-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalooThambi2-ExtraBold.ttf
          weight: 800

flutter_assets:
  assets_path: assets/
  output_path: lib/core/generated/
  filename: assets.dart
  field_prefix:
  class_name: Assets
