// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/auth/presentation/login/login_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fitness_app/features/auth/presentation/login/login_intent.dart'
    as _i6;
import 'package:fitness_app/features/auth/presentation/login/login_state.dart'
    as _i3;
import 'package:fitness_app/features/auth/presentation/login/login_view_model.dart'
    as _i4;
import 'package:flutter/widgets.dart' as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextEditingController_0 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_1<T extends _i2.State<_i2.StatefulWidget>>
    extends _i1.SmartFake
    implements _i2.GlobalKey<T> {
  _FakeGlobalKey_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginState_3 extends _i1.SmartFake implements _i3.LoginState {
  _FakeLoginState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginViewModel extends _i1.Mock implements _i4.LoginViewModel {
  MockLoginViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TextEditingController get emailController =>
      (super.noSuchMethod(
            Invocation.getter(#emailController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#emailController),
            ),
          )
          as _i2.TextEditingController);

  @override
  _i2.TextEditingController get passwordController =>
      (super.noSuchMethod(
            Invocation.getter(#passwordController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#passwordController),
            ),
          )
          as _i2.TextEditingController);

  @override
  _i2.GlobalKey<_i2.FormState> get formKey =>
      (super.noSuchMethod(
            Invocation.getter(#formKey),
            returnValue: _FakeGlobalKey_1<_i2.FormState>(
              this,
              Invocation.getter(#formKey),
            ),
          )
          as _i2.GlobalKey<_i2.FormState>);

  @override
  _i2.ValueNotifier<bool> get isPasswordVisible =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordVisible),
            returnValue: _FakeValueNotifier_2<bool>(
              this,
              Invocation.getter(#isPasswordVisible),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  bool get isFormValid =>
      (super.noSuchMethod(Invocation.getter(#isFormValid), returnValue: false)
          as bool);

  @override
  set emailController(_i2.TextEditingController? _emailController) =>
      super.noSuchMethod(
        Invocation.setter(#emailController, _emailController),
        returnValueForMissingStub: null,
      );

  @override
  set passwordController(_i2.TextEditingController? _passwordController) =>
      super.noSuchMethod(
        Invocation.setter(#passwordController, _passwordController),
        returnValueForMissingStub: null,
      );

  @override
  set formKey(_i2.GlobalKey<_i2.FormState>? _formKey) => super.noSuchMethod(
    Invocation.setter(#formKey, _formKey),
    returnValueForMissingStub: null,
  );

  @override
  set isPasswordVisible(_i2.ValueNotifier<bool>? _isPasswordVisible) =>
      super.noSuchMethod(
        Invocation.setter(#isPasswordVisible, _isPasswordVisible),
        returnValueForMissingStub: null,
      );

  @override
  set emailError(String? _emailError) => super.noSuchMethod(
    Invocation.setter(#emailError, _emailError),
    returnValueForMissingStub: null,
  );

  @override
  set passwordError(String? _passwordError) => super.noSuchMethod(
    Invocation.setter(#passwordError, _passwordError),
    returnValueForMissingStub: null,
  );

  @override
  set isFormValid(bool? _isFormValid) => super.noSuchMethod(
    Invocation.setter(#isFormValid, _isFormValid),
    returnValueForMissingStub: null,
  );

  @override
  _i3.LoginState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLoginState_3(this, Invocation.getter(#state)),
          )
          as _i3.LoginState);

  @override
  _i5.Stream<_i3.LoginState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.LoginState>.empty(),
          )
          as _i5.Stream<_i3.LoginState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loginIntent(_i6.LoginIntent? intent) => super.noSuchMethod(
    Invocation.method(#loginIntent, [intent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void emit(_i3.LoginState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i3.LoginState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
