// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/exercise/data/repo_impl/exercise_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/exercise/data/data_sources/remote/exercise_remote_ds_interface.dart'
    as _i2;
import 'package:fitness_app/features/exercise/data/models/difficulty_level/model/difficulty_level_dm.dart'
    as _i5;
import 'package:fitness_app/features/exercise/data/models/exercise/model/exercise_dm.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExerciseRemoteDsInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRemoteDsInterface extends _i1.Mock
    implements _i2.ExerciseRemoteDsInterface {
  MockExerciseRemoteDsInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.DifficultyLevelDM>>> getLevels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLevels,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<List<_i5.DifficultyLevelDM>>>.value(
                _i6.dummyValue<_i4.ApiResult<List<_i5.DifficultyLevelDM>>>(
          this,
          Invocation.method(
            #getLevels,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.DifficultyLevelDM>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i7.ExerciseDM>>> getExercises({
    required String? levelId,
    required String? muscleGroupId,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [],
          {
            #levelId: levelId,
            #muscleGroupId: muscleGroupId,
            #page: page,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i7.ExerciseDM>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i7.ExerciseDM>>>(
          this,
          Invocation.method(
            #getExercises,
            [],
            {
              #levelId: levelId,
              #muscleGroupId: muscleGroupId,
              #page: page,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i7.ExerciseDM>>>);
}
