// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/exercise/presentation/bloc/exercise_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/exercise/domain/entites/difficulty_level.dart'
    as _i5;
import 'package:fitness_app/features/exercise/domain/entites/exercise_entity.dart'
    as _i8;
import 'package:fitness_app/features/exercise/domain/use_cases/get_exercise_use_case.dart'
    as _i7;
import 'package:fitness_app/features/exercise/domain/use_cases/get_levels_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetLevelsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLevelsUseCase extends _i1.Mock implements _i2.GetLevelsUseCase {
  MockGetLevelsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.DifficultyLevelEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<List<_i5.DifficultyLevelEntity>>>.value(
                _i6.dummyValue<_i4.ApiResult<List<_i5.DifficultyLevelEntity>>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.DifficultyLevelEntity>>>);
}

/// A class which mocks [GetExercisesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExercisesUseCase extends _i1.Mock
    implements _i7.GetExercisesUseCase {
  MockGetExercisesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>> call(
    String? muscleGroupId,
    String? levelId, {
    int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            muscleGroupId,
            levelId,
          ],
          {#page: page},
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i8.ExerciseEntity>>>(
          this,
          Invocation.method(
            #call,
            [
              muscleGroupId,
              levelId,
            ],
            {#page: page},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i8.ExerciseEntity>>>);
}
