// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/food_recommendation/presentation/cubit/food_recommendation_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/food_recommendation/data/models/meals_categories_response/food_category.dart'
    as _i5;
import 'package:fitness_app/features/food_recommendation/data/models/meals_on_category_response/meal.dart'
    as _i8;
import 'package:fitness_app/features/food_recommendation/domain/usecases/get_meals_categories_use_case.dart'
    as _i2;
import 'package:fitness_app/features/food_recommendation/domain/usecases/get_meals_on_category_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetMealsCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealsCategoriesUseCase extends _i1.Mock
    implements _i2.GetMealsCategoriesUseCase {
  MockGetMealsCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.FoodCategory>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i5.FoodCategory>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i5.FoodCategory>>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i5.FoodCategory>>>);
}

/// A class which mocks [GetMealsOnCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealsOnCategoryUseCase extends _i1.Mock
    implements _i7.GetMealsOnCategoryUseCase {
  MockGetMealsOnCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i8.Meal>>> call(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [category],
        ),
        returnValue: _i3.Future<_i4.ApiResult<List<_i8.Meal>>>.value(
            _i6.dummyValue<_i4.ApiResult<List<_i8.Meal>>>(
          this,
          Invocation.method(
            #call,
            [category],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<List<_i8.Meal>>>);
}
