// test/features/home/data/datasource/remote_data_source/mocks.mocks.dart
// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/home/data/datasource/remote_data_source/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/home/data/datasource/remote_data_source/home_remote_data_source_contract.dart'
    as _i2;
import 'package:fitness_app/features/home/data/model/daily_recomendation_exercise/daily_recommendation_response.dart'
    as _i5;
import 'package:fitness_app/features/home/data/model/food_recomendation/food_recomendation/food_recomendation.dart'
    as _i7;
import 'package:fitness_app/features/home/data/model/upcoming_workouts/tabs/upcoming_tapbar/muscles_group.dart'
    as _i12;
import 'package:fitness_app/features/home/data/model/upcoming_workouts/tabs/upcoming_tapbar/upcoming_tapbar.dart'
    as _i8;
import 'package:fitness_app/features/home/data/model/upcoming_workouts/workout_by_group/workout_by_group_response.dart'
    as _i9;
import 'package:fitness_app/features/home/domain/entities/daily_recommendation_item.dart'
    as _i11;
import 'package:fitness_app/features/home/domain/entities/workout_by_group_item.dart'
    as _i13;
import 'package:fitness_app/features/home/domain/repo/home_repository_contract.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i2.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
      _i4.ApiResult<_i5.DailyRecommendationResponse>> getDailyRecommendations({
    required String? targetMuscleGroupId,
    required String? difficultyLevelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyRecommendations,
          [],
          {
            #targetMuscleGroupId: targetMuscleGroupId,
            #difficultyLevelId: difficultyLevelId,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>.value(
                _i6.dummyValue<_i4.ApiResult<_i5.DailyRecommendationResponse>>(
          this,
          Invocation.method(
            #getDailyRecommendations,
            [],
            {
              #targetMuscleGroupId: targetMuscleGroupId,
              #difficultyLevelId: difficultyLevelId,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.FoodRecomendation>> getFoodRecommendations() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecommendations, []),
            returnValue: _i3.Future<_i4.ApiResult<_i7.FoodRecomendation>>.value(
              _i6.dummyValue<_i4.ApiResult<_i7.FoodRecomendation>>(
                this,
                Invocation.method(#getFoodRecommendations, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i7.FoodRecomendation>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.UpcomingTapbar>> getMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroups, []),
            returnValue: _i3.Future<_i4.ApiResult<_i8.UpcomingTapbar>>.value(
              _i6.dummyValue<_i4.ApiResult<_i8.UpcomingTapbar>>(
                this,
                Invocation.method(#getMuscleGroups, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i8.UpcomingTapbar>>);

  @override
  _i3.Future<_i4.ApiResult<_i9.WorkoutByGroupResponse>>
  getWorkoutsByMuscleGroupId(String? muscleGroupId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByMuscleGroupId, [muscleGroupId]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i9.WorkoutByGroupResponse>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i9.WorkoutByGroupResponse>>(
                    this,
                    Invocation.method(#getWorkoutsByMuscleGroupId, [
                      muscleGroupId,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i9.WorkoutByGroupResponse>>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i10.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
      _i4.ApiResult<_i5.DailyRecommendationResponse>> getDailyRecommendations({
    required String? targetMuscleGroupId,
    required String? difficultyLevelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyRecommendations,
          [],
          {
            #targetMuscleGroupId: targetMuscleGroupId,
            #difficultyLevelId: difficultyLevelId,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>.value(
                _i6.dummyValue<_i4.ApiResult<_i5.DailyRecommendationResponse>>(
          this,
          Invocation.method(
            #getDailyRecommendations,
            [],
            {
              #targetMuscleGroupId: targetMuscleGroupId,
              #difficultyLevelId: difficultyLevelId,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i11.DailyRecommendationItem>>>
  getFoodRecommendations() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecommendations, []),
            returnValue: _i3.Future<
              _i4.ApiResult<List<_i11.DailyRecommendationItem>>
            >.value(
              _i6.dummyValue<_i4.ApiResult<List<_i11.DailyRecommendationItem>>>(
                this,
                Invocation.method(#getFoodRecommendations, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<List<_i11.DailyRecommendationItem>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i12.MusclesGroup>>> getMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroups, []),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i12.MusclesGroup>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i12.MusclesGroup>>>(
                    this,
                    Invocation.method(#getMuscleGroups, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i12.MusclesGroup>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i13.WorkoutByGroupItem>>>
  getWorkoutsByMuscleGroupId(String? muscleGroupId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByMuscleGroupId, [muscleGroupId]),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i13.WorkoutByGroupItem>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i13.WorkoutByGroupItem>>>(
                    this,
                    Invocation.method(#getWorkoutsByMuscleGroupId, [
                      muscleGroupId,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i13.WorkoutByGroupItem>>>);
}
