// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/home/data/datasource/remote_data_source/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/home/data/datasource/remote_data_source/home_remote_data_source_contract.dart'
    as _i2;
import 'package:fitness_app/features/home/data/model/daily_recomendation_exercise/daily_recommendation_response.dart'
    as _i5;
import 'package:fitness_app/features/home/data/model/food_recomendation/food_recomendation/food_recomendation.dart'
    as _i8;
import 'package:fitness_app/features/home/data/model/upcoming_workouts/upcoming_workouts/upcoming_workouts.dart'
    as _i7;
import 'package:fitness_app/features/home/domain/entities/daily_recommendation_item.dart'
    as _i10;
import 'package:fitness_app/features/home/domain/repo/home_repository_contract.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i2.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>
  getDailyRecommendations({
    required String? targetMuscleGroupId,
    required String? difficultyLevelId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyRecommendations, [], {
              #targetMuscleGroupId: targetMuscleGroupId,
              #difficultyLevelId: difficultyLevelId,
            }),
            returnValue: _i3.Future<
              _i4.ApiResult<_i5.DailyRecommendationResponse>
            >.value(
              _i6.dummyValue<_i4.ApiResult<_i5.DailyRecommendationResponse>>(
                this,
                Invocation.method(#getDailyRecommendations, [], {
                  #targetMuscleGroupId: targetMuscleGroupId,
                  #difficultyLevelId: difficultyLevelId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.UpcomingWorkouts>> getUpcomingWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingWorkouts, []),
            returnValue: _i3.Future<_i4.ApiResult<_i7.UpcomingWorkouts>>.value(
              _i6.dummyValue<_i4.ApiResult<_i7.UpcomingWorkouts>>(
                this,
                Invocation.method(#getUpcomingWorkouts, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i7.UpcomingWorkouts>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.FoodRecomendation>> getFoodRecommendations() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecommendations, []),
            returnValue: _i3.Future<_i4.ApiResult<_i8.FoodRecomendation>>.value(
              _i6.dummyValue<_i4.ApiResult<_i8.FoodRecomendation>>(
                this,
                Invocation.method(#getFoodRecommendations, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i8.FoodRecomendation>>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i9.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>
  getDailyRecommendations({
    required String? targetMuscleGroupId,
    required String? difficultyLevelId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyRecommendations, [], {
              #targetMuscleGroupId: targetMuscleGroupId,
              #difficultyLevelId: difficultyLevelId,
            }),
            returnValue: _i3.Future<
              _i4.ApiResult<_i5.DailyRecommendationResponse>
            >.value(
              _i6.dummyValue<_i4.ApiResult<_i5.DailyRecommendationResponse>>(
                this,
                Invocation.method(#getDailyRecommendations, [], {
                  #targetMuscleGroupId: targetMuscleGroupId,
                  #difficultyLevelId: difficultyLevelId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.DailyRecommendationResponse>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i10.DailyRecommendationItem>>>
  getUpcomingWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingWorkouts, []),
            returnValue: _i3.Future<
              _i4.ApiResult<List<_i10.DailyRecommendationItem>>
            >.value(
              _i6.dummyValue<_i4.ApiResult<List<_i10.DailyRecommendationItem>>>(
                this,
                Invocation.method(#getUpcomingWorkouts, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<List<_i10.DailyRecommendationItem>>>);

  @override
  _i3.Future<_i4.ApiResult<List<_i10.DailyRecommendationItem>>>
  getFoodRecommendations() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecommendations, []),
            returnValue: _i3.Future<
              _i4.ApiResult<List<_i10.DailyRecommendationItem>>
            >.value(
              _i6.dummyValue<_i4.ApiResult<List<_i10.DailyRecommendationItem>>>(
                this,
                Invocation.method(#getFoodRecommendations, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<List<_i10.DailyRecommendationItem>>>);
}
