// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/food_recommendation/data/repositories/food_recommend_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/food_recommendation/data/datasources/food_recommend_remote_data_source.dart'
    as _i2;
import 'package:fitness_app/features/food_recommendation/data/models/meals_categories_response/meals_categories_response.dart'
    as _i5;
import 'package:fitness_app/features/food_recommendation/data/models/meals_on_category_response/meals_on_category_response.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FoodRecommendRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodRecommendRemoteDataSource extends _i1.Mock
    implements _i2.FoodRecommendRemoteDataSource {
  MockFoodRecommendRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.MealsCategoriesResponse>> getMealsCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsCategories,
          [],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.MealsCategoriesResponse>>.value(
                _i6.dummyValue<_i4.ApiResult<_i5.MealsCategoriesResponse>>(
          this,
          Invocation.method(
            #getMealsCategories,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.MealsCategoriesResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.MealsOnCategoryResponse>> getMealsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealsByCategory,
          [category],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i7.MealsOnCategoryResponse>>.value(
                _i6.dummyValue<_i4.ApiResult<_i7.MealsOnCategoryResponse>>(
          this,
          Invocation.method(
            #getMealsByCategory,
            [category],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i7.MealsOnCategoryResponse>>);
}
