// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/edit_profile/presentation/bloc/edit_profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i9;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/edit_profile/data/models/edit_profile/response/edit_profile_response.dart'
    as _i5;
import 'package:fitness_app/features/edit_profile/data/models/upload_image/upload_image_response.dart'
    as _i8;
import 'package:fitness_app/features/edit_profile/domain/usecases/edit_profile_data_usecase.dart'
    as _i2;
import 'package:fitness_app/features/edit_profile/domain/usecases/get_profile_data_usecase.dart'
    as _i10;
import 'package:fitness_app/features/edit_profile/domain/usecases/upload_profile_image_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EditProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileDataUseCase extends _i1.Mock
    implements _i2.EditProfileDataUseCase {
  MockEditProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>> call({
    String? firstName,
    String? lastName,
    String? email,
    String? weight,
    String? goal,
    String? activityLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #weight: weight,
            #goal: goal,
            #activityLevel: activityLevel,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.EditProfileResponse>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #weight: weight,
              #goal: goal,
              #activityLevel: activityLevel,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>);
}

/// A class which mocks [UploadProfileImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProfileImageUseCase extends _i1.Mock
    implements _i7.UploadProfileImageUseCase {
  MockUploadProfileImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i8.UploadImageResponse>> call(
          _i9.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [imageFile],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i8.UploadImageResponse>>.value(
            _i6.dummyValue<_i4.ApiResult<_i8.UploadImageResponse>>(
          this,
          Invocation.method(
            #call,
            [imageFile],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.UploadImageResponse>>);
}

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i10.GetProfileDataUseCase {
  MockGetProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.EditProfileResponse>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>);
}
