// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/food_recommendation/presentation/pages/food_recommendation_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/features/food_recommendation/presentation/cubit/food_intent.dart'
    as _i5;
import 'package:fitness_app/features/food_recommendation/presentation/cubit/food_recommendation_state.dart'
    as _i2;
import 'package:fitness_app/features/food_recommendation/presentation/cubit/food_recommendation_viewmodel.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFoodRecommendationState_0 extends _i1.SmartFake
    implements _i2.FoodRecommendationState {
  _FakeFoodRecommendationState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FoodRecommendationViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodRecommendationViewModel extends _i1.Mock
    implements _i3.FoodRecommendationViewModel {
  MockFoodRecommendationViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FoodRecommendationState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFoodRecommendationState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.FoodRecommendationState);

  @override
  _i4.Stream<_i2.FoodRecommendationState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.FoodRecommendationState>.empty(),
      ) as _i4.Stream<_i2.FoodRecommendationState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void doIntent(_i5.FoodIntent? intent) => super.noSuchMethod(
        Invocation.method(
          #doIntent,
          [intent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.FoodRecommendationState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i6.Change<_i2.FoodRecommendationState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
