// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/edit_profile/data/repo_impl/edit_profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:fitness_app/features/edit_profile/data/datasource/remote_data_source/edit_profile_remote_data_source_interface.dart'
    as _i4;
import 'package:fitness_app/features/edit_profile/data/models/edit_profile/response/edit_profile_response.dart'
    as _i2;
import 'package:fitness_app/features/edit_profile/data/models/upload_image/upload_image_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEditProfileResponse_0 extends _i1.SmartFake
    implements _i2.EditProfileResponse {
  _FakeEditProfileResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUploadImageResponse_1 extends _i1.SmartFake
    implements _i3.UploadImageResponse {
  _FakeUploadImageResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EditProfileRemoteDataSourceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileRemoteDataSourceInterface extends _i1.Mock
    implements _i4.EditProfileRemoteDataSourceInterface {
  MockEditProfileRemoteDataSourceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.EditProfileResponse> getProfileData() => (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue: _i5.Future<_i2.EditProfileResponse>.value(
            _FakeEditProfileResponse_0(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i5.Future<_i2.EditProfileResponse>);

  @override
  _i5.Future<_i2.EditProfileResponse> editProfileData({
    String? firstName,
    String? lastName,
    String? email,
    String? weight,
    String? goal,
    String? activityLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfileData,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #weight: weight,
            #goal: goal,
            #activityLevel: activityLevel,
          },
        ),
        returnValue: _i5.Future<_i2.EditProfileResponse>.value(
            _FakeEditProfileResponse_0(
          this,
          Invocation.method(
            #editProfileData,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #weight: weight,
              #goal: goal,
              #activityLevel: activityLevel,
            },
          ),
        )),
      ) as _i5.Future<_i2.EditProfileResponse>);

  @override
  _i5.Future<_i3.UploadImageResponse> uploadProfileImage(_i6.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfileImage,
          [imageFile],
        ),
        returnValue: _i5.Future<_i3.UploadImageResponse>.value(
            _FakeUploadImageResponse_1(
          this,
          Invocation.method(
            #uploadProfileImage,
            [imageFile],
          ),
        )),
      ) as _i5.Future<_i3.UploadImageResponse>);
}
