// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/home/presentation/bloc/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/core/helper/api_result.dart' as _i5;
import 'package:fitness_app/features/home/data/model/daily_recomendation_exercise/daily_recommendation_response.dart'
    as _i6;
import 'package:fitness_app/features/home/domain/entities/daily_recommendation_item.dart'
    as _i9;
import 'package:fitness_app/features/home/domain/repo/home_repository_contract.dart'
    as _i2;
import 'package:fitness_app/features/home/domain/usecases/get_daily_recommendations_usecase.dart'
    as _i3;
import 'package:fitness_app/features/home/domain/usecases/get_food_recommendations.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetDailyRecommendationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDailyRecommendationsUseCase extends _i1.Mock
    implements _i3.GetDailyRecommendationsUseCase {
  MockGetDailyRecommendationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.DailyRecommendationResponse>> call({
    required String? targetMuscleGroupId,
    required String? difficultyLevelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #targetMuscleGroupId: targetMuscleGroupId,
            #difficultyLevelId: difficultyLevelId,
          },
        ),
        returnValue:
            _i4.Future<_i5.ApiResult<_i6.DailyRecommendationResponse>>.value(
                _i7.dummyValue<_i5.ApiResult<_i6.DailyRecommendationResponse>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #targetMuscleGroupId: targetMuscleGroupId,
              #difficultyLevelId: difficultyLevelId,
            },
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<_i6.DailyRecommendationResponse>>);
}

/// A class which mocks [GetFoodRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFoodRecommendations extends _i1.Mock
    implements _i8.GetFoodRecommendations {
  MockGetFoodRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HomeRepository);

  @override
  _i4.Future<_i5.ApiResult<List<_i9.DailyRecommendationItem>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4
            .Future<_i5.ApiResult<List<_i9.DailyRecommendationItem>>>.value(
            _i7.dummyValue<_i5.ApiResult<List<_i9.DailyRecommendationItem>>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i5.ApiResult<List<_i9.DailyRecommendationItem>>>);
}
