// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/edit_profile/domain/use_case/edit_profile_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i8;

import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/edit_profile/data/models/edit_profile/response/edit_profile_response.dart'
    as _i5;
import 'package:fitness_app/features/edit_profile/data/models/upload_image/upload_image_response.dart'
    as _i7;
import 'package:fitness_app/features/edit_profile/domain/repo/editprofile_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EditProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileRepo extends _i1.Mock implements _i2.EditProfileRepo {
  MockEditProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>> getProfileData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.EditProfileResponse>>(
          this,
          Invocation.method(
            #getProfileData,
            [],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>> editProfileData({
    String? firstName,
    String? lastName,
    String? email,
    String? weight,
    String? goal,
    String? activityLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfileData,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #weight: weight,
            #goal: goal,
            #activityLevel: activityLevel,
          },
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>.value(
            _i6.dummyValue<_i4.ApiResult<_i5.EditProfileResponse>>(
          this,
          Invocation.method(
            #editProfileData,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #weight: weight,
              #goal: goal,
              #activityLevel: activityLevel,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.UploadImageResponse>> uploadProfileImage(
          _i8.File? imageFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfileImage,
          [imageFile],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i7.UploadImageResponse>>.value(
            _i6.dummyValue<_i4.ApiResult<_i7.UploadImageResponse>>(
          this,
          Invocation.method(
            #uploadProfileImage,
            [imageFile],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i7.UploadImageResponse>>);
}
