// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/auth/data/datasource/remote_data_source/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/app_local_storage/app_secure_storage.dart'
    as _i14;
import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:fitness_app/features/auth/data/datasource/remote_data_source/auth_remote_data_source_contract.dart'
    as _i2;
import 'package:fitness_app/features/auth/data/model/forgetPassword/forgetpassword_request.dart'
    as _i10;
import 'package:fitness_app/features/auth/data/model/forgetPassword/resetpassword_request.dart'
    as _i13;
import 'package:fitness_app/core/app_data/common_response/reset_password_response.dart'
    as _i12;
import 'package:fitness_app/features/auth/data/model/forgetPassword/verify_otp_request.dart'
    as _i11;
import 'package:fitness_app/features/auth/data/model/login_models/login_request/login_request.dart'
    as _i6;
import 'package:fitness_app/features/auth/data/model/login_models/login_response/login_response.dart'
    as _i5;
import 'package:fitness_app/features/auth/data/model/register/register_request.dart'
    as _i9;
import 'package:fitness_app/features/auth/data/model/register/register_response/register_response.dart'
    as _i8;
import 'package:fitness_app/features/auth/data/model/register_details.dart'
    as _i16;
import 'package:fitness_app/features/auth/domain/repo/auth_repo.dart' as _i15;
import 'package:fitness_app/features/auth/domain/usecases/login_use_case.dart'
    as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceContract extends _i1.Mock
    implements _i2.AuthRemoteDataSourceContract {
  MockAuthRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginResponse>> login(
          _i6.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.LoginResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.LoginResponse>>(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.LoginResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.RegisterResponse>> register(
          _i9.RegisterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i8.RegisterResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i8.RegisterResponse>>(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.RegisterResponse>>);

  @override
  _i3.Future<void> forgotPassword(_i10.ForgetpasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> verifyOtp(_i11.VerifyOtpRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponse>> resetPassword(
          _i13.ResetpasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponse>>.value(
                _i7.dummyValue<_i4.ApiResult<_i12.ResetPasswordResponse>>(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i12.ResetPasswordResponse>>);
}

/// A class which mocks [AppSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSecureStorage extends _i1.Mock implements _i14.AppSecureStorage {
  MockAppSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveUserData(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [key],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> removeUserData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeUserData,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> removeToken() => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> saveRememberMe(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #saveRememberMe,
          [value],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> removeUserId() => (super.noSuchMethod(
        Invocation.method(
          #removeUserId,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getRememberMe() => (super.noSuchMethod(
        Invocation.method(
          #getRememberMe,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setLanguage(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [languageCode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getLanguage,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i15.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginResponse>> login(
          _i6.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.LoginResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.LoginResponse>>(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.LoginResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.RegisterResponse>> register(
          _i16.RegisterDetailsData? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [data],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i8.RegisterResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i8.RegisterResponse>>(
          this,
          Invocation.method(
            #register,
            [data],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.RegisterResponse>>);

  @override
  _i3.Future<void> forgotPassword(_i10.ForgetpasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> verifyOtp(_i11.VerifyOtpRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resetPassword(_i13.ResetpasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i17.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginResponse>> call(
          _i6.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [loginRequest],
        ),
        returnValue: _i3.Future<_i4.ApiResult<_i5.LoginResponse>>.value(
            _i7.dummyValue<_i4.ApiResult<_i5.LoginResponse>>(
          this,
          Invocation.method(
            #call,
            [loginRequest],
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.LoginResponse>>);
}
