// Mocks generated by Mockito 5.4.4 from annotations
// in fitness_app/test/features/exercise/data/data_sources/remote/exercise_remote_ds_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/api/api_client.dart' as _i2;
import 'package:fitness_app/core/helper/api_result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<T>> get<T>(
    String? path, {
    String? baseUrl,
    Map<String, dynamic>? queryParameters,
    bool? requiresToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #baseUrl: baseUrl,
            #queryParameters: queryParameters,
            #requiresToken: requiresToken,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #baseUrl: baseUrl,
              #queryParameters: queryParameters,
              #requiresToken: requiresToken,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> post<T>(
    String? path, {
    dynamic data,
    String? baseUrl,
    Map<String, dynamic>? queryParameters,
    bool? requiresToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #baseUrl: baseUrl,
            #queryParameters: queryParameters,
            #requiresToken: requiresToken,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #baseUrl: baseUrl,
              #queryParameters: queryParameters,
              #requiresToken: requiresToken,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> put<T>(
    String? path, {
    dynamic data,
    String? baseUrl,
    Map<String, dynamic>? queryParameters,
    bool? requiresToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #baseUrl: baseUrl,
            #queryParameters: queryParameters,
            #requiresToken: requiresToken,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #baseUrl: baseUrl,
              #queryParameters: queryParameters,
              #requiresToken: requiresToken,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> delete<T>(
    String? path, {
    String? baseUrl,
    Map<String, dynamic>? queryParameters,
    bool? requiresToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #baseUrl: baseUrl,
            #queryParameters: queryParameters,
            #requiresToken: requiresToken,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #baseUrl: baseUrl,
              #queryParameters: queryParameters,
              #requiresToken: requiresToken,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);

  @override
  _i3.Future<_i4.ApiResult<T>> patch<T>(
    String? path, {
    dynamic data,
    String? baseUrl,
    Map<String, dynamic>? queryParameters,
    bool? requiresToken = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #baseUrl: baseUrl,
            #queryParameters: queryParameters,
            #requiresToken: requiresToken,
          },
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<T>>.value(_i5.dummyValue<_i4.ApiResult<T>>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #baseUrl: baseUrl,
              #queryParameters: queryParameters,
              #requiresToken: requiresToken,
            },
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<T>>);
}
