sonar.projectKey=Fitness_app
sonar.organization=team-4-elevate
sonar.projectName=Fitness_app
sonar.projectVersion=1.0
sonar.sources=lib
sonar.tests=test
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gr.dart,**/*.config.dart,**/generated/**,**/*.pb.dart,**/build/**
sonar.dart.coverage.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.gr.dart,**/*.config.dart,**/test/**,**/generated/**
sonar.sourceEncoding=UTF-8
